// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('Comprar Passagem', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('Comprar Passagem', async function() {
    await driver.get("https://blazedemo.com/")
    await driver.manage().window().setRect({ width: 1860, height: 942 })
    assert(await driver.findElement(By.css("h1")).getText() == "Welcome to the Simple Travel Agency!")
    {
      const dropdown = await driver.findElement(By.name("fromPort"))
      await dropdown.findElement(By.xpath("//option[. = 'Boston']")).click()
    }
    {
      const dropdown = await driver.findElement(By.name("toPort"))
      await dropdown.findElement(By.xpath("//option[. = 'Berlin']")).click()
    }
    await driver.findElement(By.css(".btn-primary")).click()
    assert(await driver.findElement(By.css("h3")).getText() == "Flights from Boston to Berlin:")
    assert(await driver.findElement(By.css("th:nth-child(1)")).getText() == "Choose")
    assert(await driver.findElement(By.css("th:nth-child(2)")).getText() == "Flight #")
    assert(await driver.findElement(By.css("th:nth-child(3)")).getText() == "Airline")
    assert(await driver.findElement(By.css("th:nth-child(6)")).getText() == "Price")
    await driver.findElement(By.css("tr:nth-child(4) .btn")).click()
    assert(await driver.findElement(By.css("h2")).getText() == "Your flight from TLV to SFO has been reserved.")
    assert(await driver.findElement(By.css("p:nth-child(8)")).getText() == "Please submit the form below to purchase the flight.")
    await driver.findElement(By.id("inputName")).click()
    await driver.findElement(By.id("inputName")).sendKeys("Joana")
    await driver.findElement(By.id("address")).click()
    await driver.findElement(By.id("address")).sendKeys("Rua Jornalista Gilberto Melo")
    await driver.findElement(By.id("city")).click()
    await driver.findElement(By.id("city")).sendKeys("Terezina")
    await driver.findElement(By.id("state")).click()
    await driver.findElement(By.id("state")).sendKeys("PL")
    await driver.findElement(By.id("zipCode")).click()
    await driver.findElement(By.id("zipCode")).sendKeys("64088-190")
    {
      const dropdown = await driver.findElement(By.id("cardType"))
      await dropdown.findElement(By.xpath("//option[. = 'American Express']")).click()
    }
    await driver.findElement(By.id("creditCardNumber")).click()
    await driver.findElement(By.id("nameOnCard")).click()
    await driver.findElement(By.id("nameOnCard")).sendKeys("Joana Teste")
    await driver.findElement(By.css(".btn-primary")).click()
    assert(await driver.findElement(By.css("h1")).getText() == "Thank you for your purchase today!")
    await driver.findElement(By.linkText("Travel The World")).click()
  })
})